Openfisca request builder
DTS-STN/rules-based-benefit-finder pull request #1
Opened 2020-08-10 19:40 UTC by Moro-Code

# Description

Replaced local calculation of benefits with call to open fisca 

## Checklist
- [ ] Update CHANGELOG.md
- [ x] Unit tests have been added/updated
- [ ] e2e tests have been added/updated

2020-08-10 20:33 UTC, var-kyle requested changes
Looks pretty good, just 1 small change with calling the error page.

2020-08-10 20:33 UTC, var-kyle commented on routes/results/results.controller.js
> +          })
I would set the status of the result as well

2020-08-11 14:28 UTC, evedube approved these changes

2020-08-11 14:30 UTC, var-kyle approved these changes
LGTM

2020-08-11 15:47 UTC, merged